### ISSUE TITLE
Raspbian Pixel Network Prefs: no provision for hidden SSID

### ISSUE THREAD

**Issue by pjfdirect** [RPi-Distro/raspberrypi-ui-mods#12]
As noted in a misplaced and closed ticket from @mintslice, the Network Preferences don't allow a hidden SSID to be specified, making connection very difficult.

The panel's list only includes any broadcasted SSIDs without an option to specify a hidden one, as commonly used by many security-conscious LAN owners.

There should be an option to select "Other network" and then specify the SSID manually.

**Comment by mintslice** [comment]
I get the whole not more secure argument, but we don't hide the said at my workplace fit security reasons, so it would be great to see this implemented.

The was some argument that the version they used didn't support hidden said, so maybe that could be fixed, added or the software used changed. This is something that's going to affect a reasonable number of users and the work around is pretty awkward.
