### ISSUE TITLE
Can i have the Source Code of the Pixel Desktop  ???

### ISSUE THREAD

**Issue by ghost** [RPi-Distro/raspberrypi-ui-mods#18]
Hello there, im looking to port Pixel Desktop to Manjaro  Distro for PC and ARM, and would love to have sources and understand how its installation works.  Would be very cool to make it more popular!

Thanks in Advance!

**Comment by XECDesign** [comment]
It's an overhaul of LXDE, so it's spread across many packages.
Most of the changes can be found here:
https://github.com/raspberrypi-ui

**Comment by edneyhelene** [comment]
Thank you so much Dear XECDesign

**Comment by lurch** [comment]
@spl237 I suspect that this issue can be closed, given that the OP has since deleted their GitHub account?

**Comment by spl237** [comment]
Done!
