### ISSUE TITLE
Latest updates and oldconffiles folder

### ISSUE THREAD

**Issue by gnanet** [RPi-Distro/raspberrypi-ui-mods#19]
Recently I observed 2 updates, which informed me about changes that caused obsolete old configuration to be moved to the oldconffiles folder. After the 2nd update i went to the oldconffiles and i see an issue in the behaviour of the postinst routine. It does not check for previous backups existence, and may unconditionally overwrite the backups.

The only point where the existence of oldconffiles is checked, where the OWNER is set:
[raspberrypi-ui-mods.postinst line 81](https://github.com/RPi-Distro/raspberrypi-ui-mods/blob/master/debian/raspberrypi-ui-mods.postinst#L81)

Also i noticed a .desktop file that should show some dialog and remove itself.
Because i have not logged into the desktop after the first update, the content of the file was doubled, looking like the routine that generating it did not overwrite, but appended the dektop entry instead

**Comment by spl237** [comment]
In recent updates, the only files that are moved into oldconffiles are ones which are not required on most systems, as they are local copies of global master files. Once moved away to the backup folder, they will not be re-created unless by the user, and if changed by the user, the most recent version of the file is the one to keep. Managing multiple backups of these files is not practical.

There is no creation of a .desktop file in the postinstall any more - that was removed for this version.

**Comment by gnanet** [comment]
To be honest, i could not even find when and how the .desktop file was created, but good to read, that in fact you also considered the possible issues, and decided wise.
