### ISSUE TITLE
apt-get purge raspberrypi-ui-mods removes /etc/network/interfaces

### ISSUE THREAD

**Issue by robertely** [RPi-Distro/raspberrypi-ui-mods#2]
This is an unexpected behavior. It can be avoided but I would still consider it a bug.

**Comment by XECDesign** [comment]
Perhaps diverting the conf file is a way to fix this. I'll look into it.

**Comment by bdlow** [comment]
Removing and purging a package that is described as "Config to customise the LXDE UI for the Raspberry Pi" should NOT result in the networking configuration being deleted.

**Comment by MattWatt** [comment]
+1 for coming across this problem trying to strip out desktop packages from Raspbian.  Completely didn't expect this, luckily I had a backup.

**Comment by XECDesign** [comment]
Should be fixed in version currently in jessie. Thank you.
