### ISSUE TITLE
lxappearance and obconf both exit with "Segmentation Fault"

### ISSUE THREAD

**Issue by COOLIRON2311** [RPi-Distro/raspberrypi-ui-mods#20]
However the issue can be fixed by moving `/usr/share/themes/PiX`.

**Comment by spl237** [comment]
I'm aware of the obconf issue, and will be fixing that when I am back in the New Year, but I can't repeat the lxappearance problem - that runs fine for me with no segfaults on my latest image.

Is there anything in particular I need to do to trigger the crash, or does it just happen as soon as you run the application?

**Comment by COOLIRON2311** [comment]
It happens instantaneously. I think the reason for that is lxappearance-obconf package.

**Comment by spl237** [comment]
OK, that would make sense - it is obconf which is crashing, in that case, not lxappearance. 

That's a known fault - I'll fix it in a week or so. For what it's worth, we don't recommend using either lxappearance or obconf to configure the system any more - both have been replaced with pipanel, but that doesn't configure as many aspects of the system as the two previous applications.
