### ISSUE TITLE
Localisation issue with the custom lxpanel profile config file

### ISSUE THREAD

**Issue by emanueleg** [RPi-Distro/raspberrypi-ui-mods#25]
Hardcoded names for both the ["Run..."](https://github.com/RPi-Distro/raspberrypi-ui-mods/blob/02199607969e9fdcfa38dac422264351583b3f36/etc/xdg/lxpanel/LXDE-pi/panels/panel#L38) and ["Shutdown..."](https://github.com/RPi-Distro/raspberrypi-ui-mods/blob/02199607969e9fdcfa38dac422264351583b3f36/etc/xdg/lxpanel/LXDE-pi/panels/panel#L45) menu items should be removed from the custom lxpanel profile config file.

Instead, the default "Run" and "Logout" lxpanel menu entries (see lxpanel-buster [`plugins/menu.c`](https://github.com/raspberrypi-ui/lxpanel-buster/blob/77133b14b7a18044d0b98b13963c99ea44c15df8/plugins/menu.c#L733)) should be modified/localised through the lxpanel po file.

**Comment by XECDesign** [comment]
@spl237

**Comment by spl237** [comment]
Fixed - many thanks.
