### ISSUE TITLE
lxde task bar, no room for menu icon 

### ISSUE THREAD

**Issue by JoeBR549** [RPi-Distro/raspberrypi-ui-mods#31]
Menu icon  does not show in task bar, though it does function.  startlxde, NOT startlxde-pi.  Mouse over Menu location causes a small icon frame to be dispalyed.

Last good lxde desktop I have is 2019-09-26-raspbian-buster, however when I do an 'apt-get upgrade' it breaks.  Icon file is there and is referenced by the task bar.  Newer Raspian releases have the issue without any apt-get update.
Issue happens on main X display and on remote xserver-xephyr (remote access from another PI or Debian PC).  Happens on remote Xephyr desktop wether if Pi is configured for local desktop or not.
Don't know about realvnc, I purge that when building the PI.
This happens on Pi3, PiZero, and Pi4
No apparent error messages.

**Comment by spl237** [comment]
> Menu icon does not show in task bar, though it does function. startlxde, NOT startlxde-pi. 

The use of startlxde is not supported - you need to use startlxde-pi on this image.
