### ISSUE TITLE
PCManFM crashes LXDE desktop

### ISSUE THREAD

**Issue by JoeBR549** [RPi-Distro/raspberrypi-ui-mods#32]
Clicking on PCManFM from desktop shortcut, causes following sequence of events.
 1 PCManFM window shows up for a few moments
 2 entire desktop clears to empty image
 3 desktop icons return and other app frames return.
 4 No PCManFM

-- startlxde, NOT startlxde-pi  -- used "sudo update-alternatives --config x-session-manager"  and selected "3 manual startlxde"
2019-09-26-raspbian-buster and 2020-08-20-raspios-buster-armhf images are OK until after apt-get upgrade
Issue happens on main X display (if pi configured to boot with one) and on remote xserver-xephyr (remote access from another PI or Debian PC.  Not tested from Windows Cygwin xterminal). Happens on remote Xephyr desktop whether  Pi is configured to run a local desktop or not.
Don't know about realvnc, I purge that when building the PI.
This happens on Pi3.  Not tested on PiZero or Pi4

**Comment by spl237** [comment]
> -- startlxde, NOT startlxde-pi -- used "sudo update-alternatives --config x-session-manager" and selected "3 manual startlxde"

The use of startlxde is not supported - you need to use startlxde-pi on this image.
