### ISSUE TITLE
.svg icons and PiX theme.

### ISSUE THREAD

**Issue by b1ack0p** [RPi-Distro/raspberrypi-ui-mods#43]
Hi,

I am not sure if this is correct place and appropriate to ask but is it possible to release .svg formats of PiXflat (and old PiX) icons instead of .png? I am trying to do some additional custom icons myself via inkscape but it is being struggling to edit/create some stock icons to inherit less to gnome icon set. if icons were released in .svg format that would be perfect :)

and lastly, is it possible to maintain old PiX theme too? it feels a bit buggy. some bars and menu items go unscaled sometimes. I know it is old theme but blue theme is good to have with old PiX icons to make desktop retro-ish look.

best regards.

**Comment by spl237** [comment]
I'm really sorry, but work on themes and icons is really time-intensive, and we don't have the resource to do either of the things you request.

In general, rescaling the 48x48 icons looks ok at most sizes; SVG scaling is pretty processor intensive and gives less good control over the end result.
