### ISSUE TITLE
Bad text contrast with new PiXFlat dark theme

### ISSUE THREAD

**Issue by Botspot** [RPi-Distro/raspberrypi-ui-mods#48]
Problems encountered:
1. URLs are nearly impossible to read.
2. Text on unfocused windows has poor contrast.
![20231214_18h43m09s_grim](https://github.com/RPi-Distro/raspberrypi-ui-mods/assets/54716352/fe68a576-f865-410a-9695-542278ca6111)
This makes it hard to interact with another program while referring back to a text editor.
![20231214_18h46m14s_grim](https://github.com/RPi-Distro/raspberrypi-ui-mods/assets/54716352/dbb50c21-20fc-4761-9e0e-97e01ebaa682)
3. The QT theme matches very well, until you encounter "sort by" bars on lists. Example below is VLC's playlist view. It is impossible to read the white text on the white bar.
![20231214_18h47m47s_grim](https://github.com/RPi-Distro/raspberrypi-ui-mods/assets/54716352/1cf2ed94-6079-434b-8e54-0b667ca04446)
4. I spotted this black text color on `gnome-screenshot`
![20231214_18h50m48s_grim](https://github.com/RPi-Distro/raspberrypi-ui-mods/assets/54716352/15a7f986-93a5-451b-86e8-78198cf7e9de)
5. Very bad contrast on Add/Remove Software program
![20231214_18h52m13s_grim](https://github.com/RPi-Distro/raspberrypi-ui-mods/assets/54716352/2030f776-779e-4ff9-8e49-890c55a3606e)

**Comment by Botspot** [comment]
And overall, I think this rendition of the dark theme is missing out on its true potential. In my opinion it would look much better if large background areas were darkened a bit more.
Example below is Github's builtin dark mode.
![20231215_12h28m18s_grim](https://github.com/RPi-Distro/raspberrypi-ui-mods/assets/54716352/6574037d-74cc-4566-9186-1778dd8cf736)
This has very good contrast and is very easy on the eyes, while PiXFlat feels almost foggy or muddy in comparison.

**Comment by ghollingworth** [comment]
If you want to propose something different that’s what pull requests are for… If you just want to vent then that’s what the forums are for.

**Comment by Botspot** [comment]
> If you want to propose something different that’s what pull requests are for… If you just want to vent then that’s what the forums are for.

That is understandable, but it seemed to me that constructive feedback was requested.
![20231215_17h17m46s_grim](https://github.com/RPi-Distro/raspberrypi-ui-mods/assets/54716352/4031a4b9-943a-4dc2-8586-f2b1308b9caf)

**Comment by Botspot** [comment]
@spl237 Would you be willing to review the text contrast issues identified and check if they are easy to resolve?

**Comment by ghollingworth** [comment]
I'm sure he will have a look when he's back from his vacation, but that won't be until January now.

**Comment by Botspot** [comment]
6. The buttons and footer on the Advanced Options for the Network plugin have a strange gradient and were clearly not themed this way purposefully.
![20240101_09h56m05s_grim](https://github.com/RPi-Distro/raspberrypi-ui-mods/assets/54716352/996c39c5-8f78-42fb-bcb0-8e1a4209e297)
7. Bad text contrast when selecting Other Locations on the gtk file chooser.
![20240101_09h59m30s_grim](https://github.com/RPi-Distro/raspberrypi-ui-mods/assets/54716352/dac9cf15-0223-495e-aeab-07cadee7bb58)

**Comment by Botspot** [comment]
8. In galculator, the selected calculation modes are displayed in black instead of white. ![20240101_11h06m55s_grim](https://github.com/RPi-Distro/raspberrypi-ui-mods/assets/54716352/5479b953-bf1e-416c-880a-2f4af8e8f9d7)

**Comment by spl237** [comment]
1. In which application?
2. Text on background windows is intentionally reduced in contrast, as it is with the light theme. In response to your feedback, I have lightened it slightly, but the intention is that the foreground window should have noticeably more text contrast than other windows.
3. Fixed
4. That text is light-coloured for me, not black. Try updating.
5. Improved as a result of 2.
6. Fixed
7. Fixed
8. Probably hard-coded colour in the calculator app rather than themable, but black is readable against grey anyway, so won't be changed.

**Comment by Botspot** [comment]
11. The URL colour in an editable text-info field should be lightened.
    This can be reproduced with a yad dialog.
    Install yad: 
    ```
    sudo apt install yad
    ```
    Then run this simple test window
    ```
    echo -e 'normal text\nhttps://example.com' | yad --text-info --show-uri --width=250
    ```
    Screenshot:
    ![20240102_09h20m30s_grim](https://github.com/RPi-Distro/raspberrypi-ui-mods/assets/54716352/263c3167-e73a-4a47-af2d-c689608ad30a)
    It's possible the URL color is hardcoded into YAD, but any such option is not exposed to the user so I assume the colour is set somewhere in the GTK theme.

**Comment by spl237** [comment]
I think you are now mostly into personal preference rather than actual problems. I may revisit some of these at some point in the future, but I need to move onto other things; if people have major contrast issues with the dark theme, then the obvious solution is to use the light theme.

**Comment by Botspot** [comment]
12. Bad text contrast on 'choose file' window when unfocused
![20240102_11h06m11s_grim](https://github.com/RPi-Distro/raspberrypi-ui-mods/assets/54716352/3ba7a78f-4de8-4082-940f-442acf12014c)

**Comment by Botspot** [comment]
> I think you are now mostly into personal preference rather than actual problems. I may revisit some of these at some point in the future, but I now need to move onto other things; if you or anyone else still have major contrast issues with the dark theme, then the obvious solution is to use the light theme.

That is fine with me and I understand. For my side, I will continue using the dark theme and continue reporting any newly discovered issues. If for nothing else, this issue could serve as a record of known issues to help prevent duplicates.
IMHO, the only remaining 'major' unresolved issue is the URL color mentioned in 1. Would that be an easy fix?

**Comment by spl237** [comment]
>  IMHO, the only remaining 'major' unresolved issue is the URL color mentioned in 1. Would that be an easy fix?

It ought to be, but on the other hand, there is something unusual going on as I have not changed the URL colour from the default blue used in the light theme, and indeed some URLs still display in the correct blue anyway. So I suspect this isn't as simple as URLs are now all the wrong colour, because some of them (including the one in the widget factory tool I use for theme design) are correct. If I get a chance I will have a look now you have given an example I can repeat.

**Comment by Botspot** [comment]
> It ought to be, but on the other hand, there is something unusual going on as I have not changed the URL colour from the default blue used in the light theme, and indeed some URLs still display in the correct blue anyway. So I suspect this isn't as simple as URLs are now all the wrong colour, because some of them (including the one in the widget factory tool I use for theme design) are correct. If I get a chance I will have a look now you have given an example I can repeat.

Actually I did not give you a simplified reproducing command for the grey url issue, but only for the too dark blue url color for number 11.
Here's a modified adaptation of 11 and 1 that exhibits both bad url colors.
```
echo -e 'normal text\nhttps://example.com' | yad --text-info --show-uri --width=250 --text=$'normal text\n<a href="https://example.com">https://example.com</a>'
```
![20240102_11h27m26s_grim](https://github.com/RPi-Distro/raspberrypi-ui-mods/assets/54716352/4d46abac-36a9-4921-a8d4-982f34185b44)
Hope that helps.

**Comment by spl237** [comment]
OK, URLs should now be fixed - I've just set them to match the colour of other text; I'm not convinced that having URLs in a specific shade of light grey is particularly helpful when it comes to identifying them...

Updated theme should be in apt later on today.

**Comment by Botspot** [comment]
> OK, URLs should now be fixed - I've just set them to match the colour of other text; I'm not convinced that having URLs in a specific shade of light grey is particularly helpful when it comes to identifying them...

One is now grey, the other is unchanged. Were you planning to fix both or only the more common kind of URL?
![20240103_12h42m24s_grim](https://github.com/RPi-Distro/raspberrypi-ui-mods/assets/54716352/3c979872-5c85-46fb-9b3d-2b56d76ce583)

**Comment by spl237** [comment]
I couldn't find where the blue colour of the one below comes from. From my widget toolkits, it appears that it was actually GTK2 that used that colour for links - GTK3 uses the grey - but I couldn't find anything in the GTK2 theme files to change it. How yad is pulling colours from both GTK2 and GTK3 on the same window is a puzzle though - albeit not one I have time to investigate at the moment...
