### ISSUE TITLE
There's no easy way to connect to hidden SSID's in the GUI.

### ISSUE THREAD

**Issue by mintslice** [RPi-Distro/raspberrypi-ui-mods#5]
The Network Preferences doesn't allow you to specify a hidden SSID, making connecting very difficult.

After selecting SSID, the list only includes "non hidden" SSID's (or nothing if there are no other SSIDs) and it's not possible to specify a SSID if you're trying to connect to a hidden network.

There should be an option to select "Other network" and then specify the SSID manually.

**Comment by XECDesign** [comment]
@spl237

**Comment by spl237** [comment]
We use dhcpcd5 for networking, and a modified version of dhcpcd-gtk as the UI. It doesn't offer this functionality, so unless the author adds it, I'm afraid it won't be available in the near future.

Hiding of SSIDs is largely pointless anyway - it doesn't increase security against hacking to any significant effect, as the tools used by hackers can see networks whether or not they are broadcasting SSID. I gave up bothering with hiding SSID on my home wifi years ago...
