### ISSUE TITLE
Incorrect arrow icon on horizontal scrollbars

### ISSUE THREAD

**Issue by Botspot** [RPi-Distro/raspberrypi-ui-mods#50]
I think I would have spotted this years ago if it was always an issue, but it has been this way for most of 2024 at a minimum.

Encountered in Geany:
![20240510_15h30m29s_grim](https://github.com/RPi-Distro/raspberrypi-ui-mods/assets/54716352/df0d28da-27da-4ae8-853b-f38cb10788cd)
Encountered in Mousepad:
![20240510_15h32m47s_grim](https://github.com/RPi-Distro/raspberrypi-ui-mods/assets/54716352/f589377e-a5db-4752-9194-37122e4b58d8)
Encountered in lxtask:
![20240510_15h34m30s_grim](https://github.com/RPi-Distro/raspberrypi-ui-mods/assets/54716352/d78eef18-25b9-4e30-9fc4-268235c46638)
Notably, this seems tied to the GTK theme as QT windows and GTK4 windows are unaffected.

**Comment by spl237** [comment]
Weird. I changed those icons years ago, but not recently, and they were definitely correct when I changed them! But it looks as if something has got out of whack somewhere - I'll have a look next week.

**Comment by spl237** [comment]
Ah - I see the problem; there's an incorrect icon reference in the GTK 3 theme CSS file. Must have accidentally hit the wrong button at some point when editing something else in the file and not noticed the one letter change! Will fix now - should be in apt at some point over the next few days.

**Comment by spl237** [comment]
Fixed - was a cut-and-paste error when I was tidying the handling of symbolic icons while creating the dark theme. Well spotted!

Should be in apt by Monday.
