### ISSUE TITLE
Dark theme is broken in KDE apps like Okular

### ISSUE THREAD

**Issue by archisman-panigrahi** [RPi-Distro/raspberrypi-ui-mods#51]
I am using the dark theme in Raspberry Pi OS Bookworm.

In the toolbar in the main app, the fonts are black-on-black, and hard to read.

And for some reason, the Okular preferences Window is white-on-white (with only the text boxes being dark).

![image_2024-05-22_15-45-42](https://github.com/RPi-Distro/raspberrypi-ui-mods/assets/3063132/903d2571-b571-4f42-8827-ff6ef2feadf6)

**Comment by ghollingworth** [comment]
We do not support KDE, if you can find a fix we're happy to take it assuming it doesn't effect the Raspberry Pi OS.
