### ISSUE TITLE
Pixel upgrade issues for non "Pi" users

### ISSUE THREAD

**Issue by gbaman** [RPi-Distro/raspberrypi-ui-mods#8]
If a user uses an account that is not named "pi", none of the Pixel UI changes get applied to their account. 
The main cause of this is "pi" being hard coded into [debian/raspberrypi-ui-mods.postinst](https://github.com/RPi-Distro/raspberrypi-ui-mods/blob/master/debian/raspberrypi-ui-mods.postinst).

There are a number of reasons ranging from security to simply a family with multiple kids, why an owner may have more than 1 account on their Raspberry Pi.

It would be great if the code in [raspberrypi-ui-mods.postinst](https://github.com/RPi-Distro/raspberrypi-ui-mods/blob/master/debian/raspberrypi-ui-mods.postinst) could run on all non system user accounts on the Pi, as it can't be assumed everyone uses the "pi" user account.

**Comment by XECDesign** [comment]
postinst no longer hardcodes 'pi'
